models/Filter.php
<?php

namespace wms\packages\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use wms\packages\models\Module;

/**
 * Search represents the model behind the search form about `wms\packages\models\Module`.
 */
class Filter extends Module
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['module_id', 'module_status_id', 'module_created_at', 'module_updated_at'], 'integer'],
            [['module_name', 'module_package', 'module_settings'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     * 
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Module::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'module_id' => $this->module_id,
            'module_status_id' => $this->module_status_id,
            'module_created_at' => $this->module_created_at,
            'module_updated_at' => $this->module_updated_at,
        ]);

        $query->andFilterWhere(['like', 'module_name', $this->module_name])
            ->andFilterWhere(['like', 'module_package', $this->module_package])
            ->andFilterWhere(['like', 'module_settings', $this->module_settings]);

        return $dataProvider;
    }
}

models/Module.php
<?php

namespace wms\packages\models;

use Yii;
use wms\packages\Module as ModuleModule;
use wms\packages\models\Module\Status;

/**
 * This is the model class for table "{{%modules}}".
 *
 * @property integer $module_id
 * @property integer $module_status_id
 * @property string $module_name
 * @property string $module_package
 * @property string $module_settings
 * @property integer $module_created_at
 * @property integer $module_updated_at
 *
 * @property Module\Status $moduleStatus
 */
class Module extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return ModuleModule::tablePrefix('{{%modules}}');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['module_status_id', 'module_name', 'module_package', 'module_settings', 'module_created_at', 'module_updated_at'], 'required'],
            [['module_status_id', 'module_created_at', 'module_updated_at'], 'integer'],
            [['module_settings'], 'string'],
            [['module_name', 'module_package'], 'string', 'max' => 255],
            [['module_status_id'], 'exist', 'skipOnError' => true, 'targetClass' => Status::class, 'targetAttribute' => ['module_status_id' => 'module_status_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'module_id' => ModuleModule::t('common', 'Module ID'),
            'module_status_id' => ModuleModule::t('common', 'Module Status ID'),
            'module_name' => ModuleModule::t('common', 'Module Name'),
            'module_package' => ModuleModule::t('common', 'Module Package'),
            'module_settings' => ModuleModule::t('common', 'Module Settings'),
            'module_created_at' => ModuleModule::t('common', 'Module Created At'),
            'module_updated_at' => ModuleModule::t('common', 'Module Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Status::class, ['module_status_id' => 'module_status_id']);
    }
}

models/Search.php
<?php

namespace wms\packages\models;

use Yii;
use yii\base\Model;
use wms\packages\components\ProviderInterface;

class Search extends Model
{
    public $query;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['query'], 'required'],
            [['query'], 'string'],
        ];
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     * 
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $providerParams = [];
        
        if ($this->load($params) && $this->validate()) {
            $providerParams = [
                'searchPhrase' => $this->query
            ];
        }
        return Yii::$container->get(ProviderInterface::class, [], $providerParams);
    }
}

controllers/DefaultController.php
<?php

namespace wms\packages\controllers;

use Yii;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use wms\packages\ModuleAsset;
use wms\packages\models\Search;
use wms\packages\models\Filter;
use wms\packages\components\FinderInterface;

class DefaultController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();
        ModuleAsset::register($this->view);
    }
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'install' => ['POST'],
                    'uninstall' => ['POST'],
                ],
            ],
        ];
    }
    
    public function actionIndex()
    {
        $searchModel = new Search();
        
        $filterModel = new Filter();
        $dataProvider = $filterModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'filterModel' => $filterModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionSearch()
    {
        $searchModel = new Search();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return json_encode([
            'results' => $dataProvider->getModels()
        ]);
    }

    public function actionView($package, FinderInterface $finder)
    {
        return $this->render('view', [
            'package' => $finder->findByPackageName($package),
        ]);
    }
    
    public function actionInstall($package, FinderInterface $finder)
    {
        ;
    }
    
    public function actionUninstall($package, FinderInterface $finder)
    {
        ;
    }
}

views/default/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use wms\packages\Module;

/* @var $this yii\web\View */
/* @var $model wms\packages\models\Module */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="module-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'module_status_id')->textInput() ?>

    <?= $form->field($model, 'module_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'module_package')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'module_settings')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'module_created_at')->textInput() ?>

    <?= $form->field($model, 'module_updated_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Module::t('common', 'Create') : Module::t('common', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/default/_search.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use \yii\web\View;
use yii\web\JsExpression;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use wms\packages\Module;

/* @var $this yii\web\View */
/* @var $model wms\packages\models\Search */
/* @var $form yii\widgets\ActiveForm */

?>

<?php $form = ActiveForm::begin(); ?>

<div class="form-group has-feedback right-feedback">
    <?= $form->field($model, 'query', [
        'template' => '{input}',
        'options' => [
            'class' => 'input-group',
        ],
    ])->widget(Select2::class, [
        'theme' => Select2::THEME_BOOTSTRAP,
        'options' => [
            'placeholder' => Module::t('common', 'Search modules...'),
            'onChange' => new JsExpression('(function(input) { window.location.href = "' . Url::toRoute(['default/view', 'package' => '{{package}}']) . '".replace(encodeURI("{{package}}"), $(input).val()); })(this)'),
        ],
        'pluginOptions' => [
            'minimumInputLength' => 1,
            'ajax' => [
                'url' => Url::toRoute(['default/search']),
                'dataType' => 'json',
                'delay' => 250,
                'data' => new JsExpression('function(params) { return {\'' . Html::getInputName($model, 'query') . '\': params.term}; }'),
                'cache' => true
            ],
            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
            'templateResult' => new JsExpression('function(repo) { return wms.formatters.select2package.call(this, repo);}'),
            'templateSelection' => new JsExpression('function (repo) { return repo.package; }'),
        ],
    ]) ?>
    <span class="fa fa-search form-control-feedback text-muted" aria-hidden="true"></span>
</div>
<?php /*\yii\bootstrap\Button::widget([
    'label' => '<i class="fa fa-search"></i> ' . Module::t('common', 'Advanced search'),
    'encodeLabel' => false,
    'options' => [
        'class' => 'btn btn-success pull-right'
    ]
]);*/ ?>

<?php ActiveForm::end(); ?>

views/default/_version.php
<?php

use yii\helpers\Html;
use wms\packages\Module;

$fnUlItems = function($data, $title) {
    $items = [];
    if(is_array($data)) {
        foreach($data as $name => $value) {
            $items[] = Html::a($name, 'https://packagist.org/packages/' . $name) . ' : ' . $value;
        }
    }
    return '<strong>' . $title . '</strong>'
        . (!empty($items) ? Html::ul($items, ['encode' => false]) : '<br />' . Module::t('common', 'None'));
}

/* @var $version Packagist\Api\Result\Package\Version */
?>

<div class="version">
    <div class="row">
        <div class="col-xs-12">
            <div class="media">
                <div class="media-left">
                    <i class="fa fa-copyright"></i>
                </div>
                <div class="media-body">
                    <?= implode(', ', $version->getLicense()) ?>
                    <i class="fa fa-bookmark"></i> <?= $version->getSource()->getReference() ?>
                </div>
            </div>
            <div class="media">
                <div class="media-left">
                    <i class="fa fa-user"></i>
                </div>
                <div class="media-body">
                    <?php
                        foreach($version->getAuthors() as $author) {
                            echo '<div>' . $author->getName() . ' <' . Html::mailto($author->getEmail()) . '></div>';
                        }
                    ?>
                </div>
            </div>
            <div class="media">
                <div class="media-left">
                    <i class="fa fa-tag"></i>
                </div>
                <div class="media-body">
                    <?= implode(' ', array_map(function($value) {
                        return Html::a('#' . $value, 'https://packagist.org/search?tags=' . $value, ['class' => 'margin-r-5']);
                    }, $version->getKeywords())) ?>
                </div>
            </div>
        </div>
    </div>
    
    <br />
    
    <div class="row">
        <div class="col-xs-4">
            <?= $fnUlItems($version->getRequire(), Module::t('common', 'requires')) ?>
        </div>
        <div class="col-xs-4">
            <?= $fnUlItems($version->getRequireDev(), Module::t('common', 'requires(dev)')) ?>
        </div>
        <div class="col-xs-4">
            <?= $fnUlItems(property_exists($version, 'suggest') ? $version->suggest : null, Module::t('common', 'suggests')) ?>
        </div>
    </div>
    
    <div class="row">
        <div class="col-xs-4">
            <?= $fnUlItems($version->getProvide(), Module::t('common', 'provides')) ?>
        </div>
        <div class="col-xs-4">
            <?= $fnUlItems($version->getConflict(), Module::t('common', 'conflicts')) ?>
        </div>
        <div class="col-xs-4">
            <?= $fnUlItems($version->getReplace(), Module::t('common', 'replaces')) ?>
        </div>
    </div>
</div>

views/default/create.php
<?php

use yii\helpers\Html;
use wms\packages\Module;

/* @var $this yii\web\View */
/* @var $model wms\packages\models\Module */

$this->title = Module::t('common', 'Create Module');
$this->params['breadcrumbs'][] = ['label' => Module::t('common', 'Modules'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="module-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/default/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use wms\packages\Module;

/* @var $this yii\web\View */
/* @var $searchModel wms\packages\models\Search */
/* @var $filterModel wms\packages\models\Filter */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Module::t('common', 'Modules & Extensions');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="module-index">
    <div class="box">
        <div class="box-header">
            <div class="row no-margin">
                <div class="col-xs-8">
                    <div class="box-tools">
                        <?php /* \yii\bootstrap\ButtonGroup::widget([
                            'buttons' => [
                                \yii\bootstrap\Button::widget([
                                    'label' => Module::t('common', 'Installed'),
                                    'options' => [
                                        'class' => 'btn btn-primary'
                                    ]
                                ]),
                                \yii\bootstrap\Button::widget([
                                    'label' => Module::t('common', 'Downloaded'),
                                    'options' => [
                                        'class' => 'btn btn-default'
                                    ]
                                ]),
                            ]
                        ]);*/ ?>
                    </div>
                </div>
                <div class="col-xs-4">
                    <?= $this->render('_search', [
                        'model' => $searchModel
                    ]); ?>
                </div>
            </div>
        </div>
        <!-- /.box-header -->
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $filterModel,
            'options' => [
                'class' => 'box-body table-responsive no-padding'
            ],
            'tableOptions' => [
                'class' => 'table table-hover'
            ],
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'module_id',
                'module_status_id',
                'module_name',
                'module_package',
                'module_settings:ntext',
                // 'module_created_at',
                // 'module_updated_at',

                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
    </div>
    <!-- /.box -->
</div>

views/default/update.php
<?php

use yii\helpers\Html;
use wms\packages\Module;

/* @var $this yii\web\View */
/* @var $model wms\packages\models\Module */

$this->title = Module::t('common', 'Update {modelClass}: ', [
    'modelClass' => 'Module',
]) . ' ' . $model->module_id;
$this->params['breadcrumbs'][] = ['label' => Module::t('common', 'Modules'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->module_id, 'url' => ['view', 'id' => $model->module_id]];
$this->params['breadcrumbs'][] = Module::t('common', 'Update');
?>
<div class="module-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/default/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use wms\packages\Module;

/* @var $this yii\web\View */
/* @var $package Packagist\Api\Result\Package */

$this->title = $package->getName();
$this->params['breadcrumbs'][] = ['label' => Module::t('common', 'Modules'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="module-view">
    <section class="panel panel-default">
        <div class="panel-body">
            <!-- title row -->
            <div class="page-header row">
                <div class="col-xs-8">
                    <h2 class="h4"><?= $package->getDescription() ?></h2>
                </div>
                <div class="col-xs-4">
                    <p class="text-muted pull-right"><small><small><small><?= \Yii::$app->formatter->asDatetime($package->getTime()) ?></small></small></small></p>
                </div>
                <!-- /.col -->
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <?= \yii\bootstrap\Button::widget([
                        'label' => '<i class="fa fa-download"></i> ' . Module::t('common', 'Install'),
                        'encodeLabel' => false,
                        'options' => [
                            'class' => 'btn btn-success pull-right'
                        ]
                    ]); ?>
                </div>
            </div>
            <!-- versions row -->
            <div class="package row">
                <div class="col-xs-8">
                    <p class="lead"><?= Module::t('common', 'Versions') ?>:</p>
                    <?php
                        $items = [];
                        $active = true;
                        /* @var $version Packagist\Api\Result\Package\Version */
                        foreach($package->getVersions() as $version) {
                            $items[] = [
                                'label' => $version->getVersion(),
                                'content' => $this->render('_version', ['version' => $version]),
                                'active' => $active
                            ];
                            
                            if($active === true) {
                                $active = false;
                            }
                        }
                    ?>
                    <div class="items">
                        <?= \kartik\tabs\TabsX::widget([
                            'items' => $items,
                            'options' => ['class' => 'nav nav-pills'],
                            'encodeLabels' => false
                        ]) ?>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <p class="lead"><?= Module::t('common', 'Details') ?>:</p>
                    <?= DetailView::widget([
                        'options' => [
                            'class' => 'table'
                        ],
                        'model' => [
                            'type' => $package->getType(),
                            'time' => $package->getTime(),
                            'repository' => $package->getRepository(),
                            'installs' => $package->getDownloads()->getTotal(),
                            'stars' => $package->getFavers()
                        ],
                        'attributes' => [
                            'repository:url:' . Module::t('common', 'Repository Url'),
                            'time:datetime:' . Module::t('common', 'Last Updated'),
                            [
                                'attribute' => 'type',
                                'label' => Module::t('common', 'Type'),
                                'value' => call_user_func(function($value) {
                                    return Html::a($value, 'https://packagist.org/search?type=' . $value);
                                }, $package->getType()),
                                'format' => 'html'
                            ],
                            'installs:integer:' . Module::t('common', 'Installs'),
                            'stars:integer:' . Module::t('common', 'Stars'),
                        ]
                    ]) ?>
                </div>
            </div>
            <!-- /.row -->
        </div>
    </section>
    <!-- /.content -->
</div>